/*
 * TIMERS_Cfg.h
 *
 *  Created on: Jan 18, 2022
 *      Author: Ahmed Ibrahim
 */

#ifndef INCLUDE_MCAL_TIMER0_TIMER0_CFG_H_
#define INCLUDE_MCAL_TIMER0_TIMER0_CFG_H_

#define TIMERS_u8_OCR0_VALUE         200
#define TIMER_u8_MODE             TIMER_u8_FPWM_MODE

#define TIMER_u8_MODE_OF_FPWM    TIMER_u8_FPWM_NONINVERTING

#define TIMER_u8_OVF_INTERRUPT    DISABLE
#define TIMER_u8_CTC_INTERRUPT    DISABLE

#define TIMERS_u8_PRESCALER_VALUE  2

#endif /* INCLUDE_MCAL_TIMER0_TIMER0_CFG_H_ */
