/*
 * UART_Program.c
 *
 *  Created on: Jan 28, 2022
 *      Author: Ahmed Ibrahim
 */

#include "../Include/LIB/bit_math.h"
#include "../Include/LIB/std_type.h"

#include "../Include/MCAL/UART/UART_Cfg.h"
#include "../Include/MCAL/UART/UART_Interface.h"
#include "../Include/MCAL/UART/UART_Private.h"


void UART_voidInit(void)
{
#if (UART_DOUBLE_SPEED==ON)
	SET_BIT(UART_U8_UCSRA_REG,UART_U8_UCSRA_PIN1);
#else
	CLR_BIT(UART_U8_UCSRA_REG,UART_U8_UCSRA_PIN1);
#endif

#if (UART_MULTI_PROCESSOR==ON)
	SET_BIT(UART_U8_UCSRA_REG,UART_U8_UCSRA_PIN0);
#else
	CLR_BIT(UART_U8_UCSRA_REG,UART_U8_UCSRA_PIN0);
#endif

#if(UART_INT_POLL_MODE==INTERRUPT)
	SET_BIT(UART_U8_UCSRB_REG,UART_U8_UCSRB_PIN7);
	SET_BIT(UART_U8_UCSRB_REG,UART_U8_UCSRB_PIN6);
	SET_BIT(UART_U8_UCSRB_REG,UART_U8_UCSRB_PIN5);
#else
	CLR_BIT(UART_U8_UCSRB_REG,UART_U8_UCSRB_PIN7);
	CLR_BIT(UART_U8_UCSRB_REG,UART_U8_UCSRB_PIN6);
	CLR_BIT(UART_U8_UCSRB_REG,UART_U8_UCSRB_PIN5);
#endif

#if(UART_ASYNCH_SYNCH_MODE==ASYNCHRONOUS)
	SET_BIT(UART_U8_UCSRC_REG,UART_U8_UCSRC_PIN7);
	CLR_BIT(UART_U8_UCSRC_REG,UART_U8_UCSRC_PIN6);
#else
	SET_BIT(UART_U8_UCSRC_REG,UART_U8_UCSRC_PIN6);
#endif

	CLR_BIT(UART_U8_UCSRC_REG,UART_U8_UCSRC_PIN5);
	CLR_BIT(UART_U8_UCSRC_REG,UART_U8_UCSRC_PIN4);

	CLR_BIT(UART_U8_UCSRC_REG,UART_U8_UCSRC_PIN3);

	SET_BIT(UART_U8_UCSRC_REG,UART_U8_UCSRC_PIN2);
	SET_BIT(UART_U8_UCSRC_REG,UART_U8_UCSRC_PIN1);
	CLR_BIT(UART_U8_UCSRB_REG,UART_U8_UCSRB_PIN2);

	CLR_BIT(UART_U8_UCSRC_REG,UART_U8_UCSRC_PIN0);

	CLR_BIT(UART_U8_UBRRH_REG,UART_U8_UCSRC_PIN7);
	UART_U8_UBRRL_REG=(u8)UART_UBRR;
	UART_U8_UBRRL_REG=(UART_UBRR>>8);

	SET_BIT(UART_U8_UCSRB_REG,UART_U8_UCSRB_PIN4);
	SET_BIT(UART_U8_UCSRB_REG,UART_U8_UCSRB_PIN3);

}

void UART_voidTransmitChar(u8 local_u8_data)
{
	UART_U8_UDR_REG=local_u8_data;
	while(!GET_BIT(UART_U8_UCSRA_REG,UART_U8_UCSRA_PIN5))
		{
		}
	SET_BIT(UART_U8_UCSRA_REG,UART_U8_UCSRA_PIN6);
}

u8 UART_u8_RecieveChar(void)
{
	while(!GET_BIT(UART_U8_UCSRA_REG,UART_U8_UCSRA_PIN7))
		{
		}
	return UART_U8_UDR_REG;
}
