/*
 * DIO_Cfg.h
 *
 *  Created on: Jan 3, 2022
 *      Author: Ahmed Ibrahim
 */

#ifndef INCLUDE_MCAL_DIO_DIO_CFG_H_
#define INCLUDE_MCAL_DIO_DIO_CFG_H_


#define DIO_U8_PA0_INITIAL_DIRECTION  DIO_U8_INITIAL_OUTPUT
#define DIO_U8_PA1_INITIAL_DIRECTION  DIO_U8_INITIAL_OUTPUT
#define DIO_U8_PA2_INITIAL_DIRECTION  DIO_U8_INITIAL_OUTPUT
#define DIO_U8_PA3_INITIAL_DIRECTION  DIO_U8_INITIAL_INPUT
#define DIO_U8_PA4_INITIAL_DIRECTION  DIO_U8_INITIAL_OUTPUT
#define DIO_U8_PA5_INITIAL_DIRECTION  DIO_U8_INITIAL_OUTPUT
#define DIO_U8_PA6_INITIAL_DIRECTION  DIO_U8_INITIAL_OUTPUT
#define DIO_U8_PA7_INITIAL_DIRECTION  DIO_U8_INITIAL_OUTPUT

#define DIO_U8_PB0_INITIAL_DIRECTION  DIO_U8_INITIAL_INPUT
#define DIO_U8_PB1_INITIAL_DIRECTION  DIO_U8_INITIAL_INPUT
#define DIO_U8_PB2_INITIAL_DIRECTION  DIO_U8_INITIAL_INPUT
#define DIO_U8_PB3_INITIAL_DIRECTION  DIO_U8_INITIAL_INPUT
#define DIO_U8_PB4_INITIAL_DIRECTION  DIO_U8_INITIAL_OUTPUT
#define DIO_U8_PB5_INITIAL_DIRECTION  DIO_U8_INITIAL_OUTPUT
#define DIO_U8_PB6_INITIAL_DIRECTION  DIO_U8_INITIAL_OUTPUT
#define DIO_U8_PB7_INITIAL_DIRECTION  DIO_U8_INITIAL_OUTPUT

#define DIO_U8_PC0_INITIAL_DIRECTION  DIO_U8_INITIAL_OUTPUT
#define DIO_U8_PC1_INITIAL_DIRECTION  DIO_U8_INITIAL_OUTPUT
#define DIO_U8_PC2_INITIAL_DIRECTION  DIO_U8_INITIAL_OUTPUT
#define DIO_U8_PC3_INITIAL_DIRECTION  DIO_U8_INITIAL_OUTPUT
#define DIO_U8_PC4_INITIAL_DIRECTION  DIO_U8_INITIAL_OUTPUT
#define DIO_U8_PC5_INITIAL_DIRECTION  DIO_U8_INITIAL_OUTPUT
#define DIO_U8_PC6_INITIAL_DIRECTION  DIO_U8_INITIAL_OUTPUT
#define DIO_U8_PC7_INITIAL_DIRECTION  DIO_U8_INITIAL_OUTPUT

#define DIO_U8_PD0_INITIAL_DIRECTION  DIO_U8_INITIAL_OUTPUT
#define DIO_U8_PD1_INITIAL_DIRECTION  DIO_U8_INITIAL_OUTPUT
#define DIO_U8_PD2_INITIAL_DIRECTION  DIO_U8_INITIAL_OUTPUT
#define DIO_U8_PD3_INITIAL_DIRECTION  DIO_U8_INITIAL_OUTPUT
#define DIO_U8_PD4_INITIAL_DIRECTION  DIO_U8_INITIAL_OUTPUT
#define DIO_U8_PD5_INITIAL_DIRECTION  DIO_U8_INITIAL_OUTPUT
#define DIO_U8_PD6_INITIAL_DIRECTION  DIO_U8_INITIAL_OUTPUT
#define DIO_U8_PD7_INITIAL_DIRECTION  DIO_U8_INITIAL_OUTPUT
	 /***************************************************************/

#define DIO_U8_PA0_INITIAL_VALUE DIO_U8_OUTPUT_LOW
#define DIO_U8_PA1_INITIAL_VALUE DIO_U8_OUTPUT_LOW
#define DIO_U8_PA2_INITIAL_VALUE DIO_U8_OUTPUT_LOW
#define DIO_U8_PA3_INITIAL_VALUE DIO_U8_OUTPUT_LOW
#define DIO_U8_PA4_INITIAL_VALUE DIO_U8_OUTPUT_LOW
#define DIO_U8_PA5_INITIAL_VALUE DIO_U8_OUTPUT_LOW
#define DIO_U8_PA6_INITIAL_VALUE DIO_U8_OUTPUT_LOW
#define DIO_U8_PA7_INITIAL_VALUE DIO_U8_OUTPUT_LOW

#define DIO_U8_PB0_INITIAL_VALUE  DIO_U8_INPUT_PULLUP
#define DIO_U8_PB1_INITIAL_VALUE  DIO_U8_INPUT_PULLUP
#define DIO_U8_PB2_INITIAL_VALUE  DIO_U8_INPUT_PULLUP
#define DIO_U8_PB3_INITIAL_VALUE  DIO_U8_INPUT_PULLUP
#define DIO_U8_PB4_INITIAL_VALUE  DIO_U8_OUTPUT_LOW
#define DIO_U8_PB5_INITIAL_VALUE  DIO_U8_OUTPUT_LOW
#define DIO_U8_PB6_INITIAL_VALUE  DIO_U8_OUTPUT_LOW
#define DIO_U8_PB7_INITIAL_VALUE  DIO_U8_OUTPUT_LOW

#define DIO_U8_PC0_INITIAL_VALUE  DIO_U8_OUTPUT_LOW
#define DIO_U8_PC1_INITIAL_VALUE  DIO_U8_OUTPUT_LOW
#define DIO_U8_PC2_INITIAL_VALUE  DIO_U8_OUTPUT_LOW
#define DIO_U8_PC3_INITIAL_VALUE  DIO_U8_OUTPUT_LOW
#define DIO_U8_PC4_INITIAL_VALUE  DIO_U8_OUTPUT_LOW
#define DIO_U8_PC5_INITIAL_VALUE  DIO_U8_OUTPUT_LOW
#define DIO_U8_PC6_INITIAL_VALUE  DIO_U8_OUTPUT_LOW
#define DIO_U8_PC7_INITIAL_VALUE  DIO_U8_OUTPUT_LOW

#define DIO_U8_PD0_INITIAL_VALUE  DIO_U8_OUTPUT_LOW
#define DIO_U8_PD1_INITIAL_VALUE  DIO_U8_OUTPUT_LOW
#define DIO_U8_PD2_INITIAL_VALUE  DIO_U8_OUTPUT_LOW
#define DIO_U8_PD3_INITIAL_VALUE  DIO_U8_OUTPUT_LOW
#define DIO_U8_PD4_INITIAL_VALUE  DIO_U8_OUTPUT_LOW
#define DIO_U8_PD5_INITIAL_VALUE  DIO_U8_OUTPUT_LOW
#define DIO_U8_PD6_INITIAL_VALUE  DIO_U8_OUTPUT_LOW
#define DIO_U8_PD7_INITIAL_VALUE  DIO_U8_OUTPUT_LOW

#endif /* INCLUDE_MCAL_DIO_DIO_CFG_H_ */
